# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "65b68268-1a08-4c5b-be3a-e7871f5f1676"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  increment_version_number(
    bump_type: "minor" # Automatically increment minor version number (i.e. 20.1.4 = Major.Minor.Patch)
  )

  #Fetch or generate the latest available code signing identity
  cert
  #Generates a provisioning profile. Stores the profile in the current folder
  sigh

  #need to unlock the keychain for some reason. I'm not sure why or if this is even useful. Fastlane seems to work sometimes and not others with this line.
  unlock_keychain(path:"login.keychain", password:"basket1234")
  sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain"
  # build your iOS app
  gym(
    scheme: "Configurations Release",
    export_options: {
      provisioningProfiles: {
        "dcj.Chong500Productions.Food-For-All": "Freelancers Distrubution"
      }
    }
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: false)
end

#my app store lane is still not working. I will have to do some more debugging to get it to work.
lane :release do
  increment_version_number(
    bump_type: "minor" # Automatically increment minor version number (i.e. 20.1.4 = Major.Minor.Patch)
  )

  #Fetch or generate the latest available code signing identity
  cert
  #Generates a provisioning profile. Stores the profile in the current folder
  sigh

  # build your iOS app
  gym(
    scheme: "Configurations Release",
    export_options: {
      provisioningProfiles: {
        "dcj.Chong500Productions.Food-For-All": "Freelancers Distrubution"
      }
    }
  )

  # Upload the binary to iTunes
  deliver(
    force: true,
    submit_for_review: true,
    release_notes: "A Medici Jones original. Always releasing new features to improve the Gigio experience, just for you!"
  )                   
end
